package:
  name: explore-pipolin
  version: 0.0.1

source:
  path: ..

build:
  script: {{PYTHON}} -m pip install . --no-deps

requirements:
  build:
    - python >=3.7
    - setuptools
    - click
    - biopython <=1.76
    - bcbio-gff
    - prefect >=0.11.5

  run:
    - python >=3.7
    - click
    - biopython <=1.76
    - bcbio-gff
    - prefect >=0.11.5
    - blast
    - aragorn
    - prokka

test:
  commands:
    - explore_pipolin -h

about:
  home: https://github.com/liubovch/ExplorePipolin
  license:
  license_file: LICENSE