package:
  name: explore-pipolin
  version: 0.0.1
source:
  path: ..

build:
  noarch: python
  script: {{PYTHON}} -m pip install . --no-deps

requirements:
  build:
    - python >=3.7
    - setuptools
    - click
    - biopython <=1.76
    - bcbio-gff
    - prefect ==1.2.1
    - dataclasses

  run:
    - python >=3.7
    - click
    - biopython <=1.76
    - bcbio-gff
    - prefect ==1.2.1
    - perl-bioperl ==1.7.2
    - blast
    - aragorn
    - prokka ==1.14.6
    - dataclasses

test:
  commands:
    - explore_pipolin -h

about:
  home: https://github.com/pipolinlab/ExplorePipolin
  license: GPLv3
  license_file: LICENSE
