package:
  name: explore-pipolin
  version: 0.0.1

source:
  path: ..

build:
  noarch: python
  script: {{PYTHON}} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - setuptools
    - click
    - biopython
    - bcbio-gff
    - prefect

  run:
    - python >=3.6
    - click
    - biopython
    - bcbio-gff
    - prefect
    - blast
    - entrez-direct
    - aragorn
    - prokka

test:
  commands:
    - explore_pipolin -h

about:
  home: