package:
  name: explore-pipolin
  version: 0.0.a1

source:
  git_url: https://github.com/liubovch/ExplorePipolin.git
  git_rev: 0.0.a1
  git_depth: 1

build:
  noarch: python
  script: {{PYTHON}} -m pip install . --no-deps

requirements:
  build:
    - python >=3.6
    - setuptools
    - click
    - biopython <=1.76
    - bcbio-gff
    - prefect >=0.11.5

  run:
    - python >=3.6
    - click
    - biopython <=1.76
    - bcbio-gff
    - prefect >=0.11.5
    - blast
    - aragorn
    - prokka

test:
  commands:
    - explore_pipolin -h

about:
  home: https://github.com/liubovch/ExplorePipolin
  license:
  license_file: LICENSE